#!/bin/zsh
flutter build web --release --no-tree-shake-icons --base-href "/grammar_tutor/"
rsync -avzP --delete /Users/charles/grammar_tutor/build/web/ perng@pdx1-shared-a2-07.dreamhost.com:/home/perng/ai.perng.com/grammar_tutor/
