#!/bin/zsh
flutter build web --release --no-tree-shake-icons --base-href "/handy_grammar/"
rsync -avzP --delete /Users/charles/handy_grammar/build/web/ perng@pdx1-shared-a2-07.dreamhost.com:/home/perng/ai.perng.com/handy_grammar/
